sudo: required
language: python
python:
  - "2.7"
  - "3.5"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib future h5py xlrd
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION matplotlib numpy scipy future
script:
  - export NGPDIR=../
  - export PYTHONPATH=$PYTHONPATH:$NGPDIR
  - python -m NuGridPy.regression_tests.selftest
notifications:
  slack: nugrid:wTgGR31cFsNUqfytUDZ5ZLug
  email: false
